### ISSUE TITLE
Episodes folder structure and naming

### ISSUE THREAD

**Issue by JaroCamphuijsen** [esciencecenter-digital-skills/image-processing#13]
Would be nice if we structure the episodes directory a bit os that the episodes appear in order and with consistent naming. Also currently the numbering doesn't match with the carpentries lesson, which makes it more confusing.

I propose to use the following:

`{episodeNumber:02d}_{episodeShortName}`

This would result for example in changing the current folder `episode_1` to `02_imageBasics`.

What do others think?

**Comment by drcandacemakedamoore** [comment]
I am fine with this in principal, and as no one else objected, we just need to inform them. I will review the related PR now.
